# Generated by Django 3.2.16 on 2023-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230222_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Нормализированное название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Нормализированное название'),
        ),
    ]
