# Generated by Django 3.2.16 on 2023-02-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20230224_1822'),
        ('catalog', '0005_auto_20230223_1459'),
    ]

    operations = [
    ]
