# Generated by Django 3.2.16 on 2023-03-01 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_merge_0004_auto_20230224_1822_0005_auto_20230223_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='wadwd')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(default='', editable=False, max_length=150, verbose_name='Нормализированное название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(default='', editable=False, max_length=150, verbose_name='Нормализированное название'),
        ),
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.image'),
        ),
    ]
