# Generated by Django 3.2.16 on 2023-03-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20230301_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ImageField(null=True, upload_to='catalog/main/', verbose_name='Главное изображение'),
        ),
    ]
