# Generated by Django 3.2.16 on 2023-03-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('catalog', '0010_item_main_image'), ('catalog', '0011_auto_20230302_1055'), ('catalog', '0012_auto_20230303_2318'), ('catalog', '0013_alter_imagemodel_image'), ('catalog', '0014_item_img'), ('catalog', '0015_auto_20230304_0029')]

    dependencies = [
        ('catalog', '0009_auto_20230301_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='catalog/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Изображение'),
        ),
    ]
