# Generated by Django 3.2.16 on 2023-03-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_item_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='catalog/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.item'),
        ),
    ]
