# Generated by Django 3.2.16 on 2023-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_item_main_image_squashed_0015_auto_20230304_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False),
        ),
    ]
