# Generated by Django 3.2.16 on 2023-03-08 17:28

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('catalog', '0011_item_is_on_main'), ('catalog', '0012_alter_imagemodel_item'), ('catalog', '0013_alter_item_text')]

    dependencies = [
        ('catalog', '0010_item_main_image_squashed_0015_auto_20230304_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(validators=[catalog.validators.validate_text], verbose_name='Описание'),
        ),
    ]
