# Generated by Django 3.2.16 on 2023-03-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_item_is_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='catalog.item'),
        ),
    ]
