# Generated by Django 3.2.16 on 2023-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20230303_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Изображение'),
        ),
    ]
