# Generated by Django 3.2.16 on 2023-03-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230322_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coffee_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во чашек кофе'),
        ),
    ]
