# Generated by Django 3.2.16 on 2023-03-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('feedback', '0002_auto_20230315_1033'), ('feedback', '0003_alter_feedback_status')]

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'получено'), ('pending', 'в обработке'), ('answered', 'ответ дан')], default='pending', max_length=20),
        ),
    ]
